// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7xU1D7BkddkrCbu8dqtjShfzbXbwqKrg',
    appId: '1:354151585494:web:bb68bbdfa7a942d3561b77',
    messagingSenderId: '354151585494',
    projectId: 'bashiri-high-school',
    authDomain: 'bashiri-high-school.firebaseapp.com',
    storageBucket: 'bashiri-high-school.appspot.com',
    measurementId: 'G-DFGJK6KLFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2VDAHWIYt2IR7uV_-Goud83C23-Hg0LU',
    appId: '1:354151585494:android:db8f48d8ad0c4619561b77',
    messagingSenderId: '354151585494',
    projectId: 'bashiri-high-school',
    storageBucket: 'bashiri-high-school.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPDu_sIksZuV6tDlctD2i07g9Zr0JYva4',
    appId: '1:354151585494:ios:bf9b4645a1673abe561b77',
    messagingSenderId: '354151585494',
    projectId: 'bashiri-high-school',
    storageBucket: 'bashiri-high-school.appspot.com',
    iosClientId: '354151585494-52l29kn7e1tk48lk2gimuukcoau8ft7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.bashiriHightSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPDu_sIksZuV6tDlctD2i07g9Zr0JYva4',
    appId: '1:354151585494:ios:ed2281ee481da1ef561b77',
    messagingSenderId: '354151585494',
    projectId: 'bashiri-high-school',
    storageBucket: 'bashiri-high-school.appspot.com',
    iosClientId: '354151585494-1i71ra27m8dmqfu653b9oadt2263phnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bashiriHightSchool.RunnerTests',
  );
}
